// User types
export type UserRole = 'CONTRIBUTOR' | 'ARTIST' | 'ADMIN';

export type User = {
  id: string;
  email: string;
  name: string | null;
  image: string | null;
  bio: string | null;
  portfolio: string | null;
  role: UserRole;
  created_at: string;
  updated_at: string;
};

// Topic types
export type TopicStatus = 'active' | 'completed' | 'upcoming';

export interface ContributionTypeConfig {
  type: string;
  title: string;
  description: string;
  examples: string[];
}

export interface TopicRow {
  id: string;
  title: string;
  description: string;
  long_description: string | null;
  status: TopicStatus;
  target_contributors: number;
  deadline: string | null;
  estimated_completion: string | null;
  completed_date: string | null;
  artist_id: string | null;
  contribution_types: ContributionTypeConfig[];
  prompts: string[];
  created_at: string;
  updated_at: string;
  users?: {
    id: string;
    name: string | null;
    bio: string | null;
    portfolio: string | null;
  } | null;
}

export interface TopicStats {
  contributors: number;
  contributions: number;
  privateContributions: number;
  pendingContributions: number;
}

// Contribution types
export type ContributionType = 'story' | 'photo' | 'sound' | 'link';
export type ContributionStatus = 'pending' | 'approved' | 'rejected';

export type ContributionSource = 'community' | 'studio_seed';

export interface ContributionVersion {
  at: string;
  content: string;
  caption: string | null;
  refine_task_id: string | null;
  instructions: string | null;
}

export interface Contribution {
  id: string;
  topic_id: string;
  type: ContributionType;
  contributor_name: string;
  contributor_email: string;
  contributor_location: string | null;
  content: string;
  caption: string | null;
  consent_given: boolean;
  status: ContributionStatus;
  admin_notes: string | null;
  show_publicly: boolean;
  source: ContributionSource | null;
  previous_versions: ContributionVersion[];
  created_at: string;
  updated_at: string;
}

// Artwork types
export type ArtworkStatus = 'created' | 'listed' | 'sold';

/**
 * Listing metadata generated by the listing-generator agent and applied
 * to Shopify by the listing-sync library.
 *
 * Empty-by-default (`'{}'::jsonb`). Fields stay nullable so the operator
 * can edit individual fields manually without forcing a regen of the
 * others.
 *
 * This is the *creative* surface — fields with no canonical source in
 * the admin DB. Canonical fields (price, vendor, tags, collections)
 * stay on the artwork row / its joined records and are pushed to
 * Shopify/Gelato directly via the sync.
 */
export interface ListingMeta {
  /** SEO meta title for Shopify global.title_tag (≤60 chars). */
  seoTitle: string | null;
  /** SEO meta description for global.description_tag (≤160 chars). */
  seoDescription: string | null;
  /** Open Graph title for social shares (≤60 chars). */
  ogTitle: string | null;
  /** Open Graph description for social shares (≤200 chars). */
  ogDescription: string | null;
  /** ISO timestamp when the agent last wrote this. */
  generatedAt: string | null;
  /** Who set the current values. */
  generatedBy: 'agent' | 'manual' | null;
}

export const EMPTY_LISTING_META: ListingMeta = {
  seoTitle: null,
  seoDescription: null,
  ogTitle: null,
  ogDescription: null,
  generatedAt: null,
  generatedBy: null,
};

export type Artwork = {
  id: string;
  title: string;
  description: string | null;
  image_url: string | null;
  shopify_product_id: string | null;
  shopify_handle: string | null;
  gelato_product_id: string | null;
  gelato_store_id: string | null;
  artist_id: string | null;
  topic_id: string | null;
  status: ArtworkStatus;
  edition_size: number | null;
  edition_sold: number;
  price: number | null;
  currency: string;
  product_type: string | null;
  creation_date: string | null;
  inspiration_summary: string | null;
  contributor_count: number;
  listing_meta: ListingMeta | null;
  created_at: string;
  updated_at: string;
};
