// User types
export type UserRole = 'CONTRIBUTOR' | 'ARTIST' | 'ADMIN';

// Artist provenance taxonomy (migration 027). Internal bookkeeping only.
//   studio:    house AI personas we created
//   community: real people we onboard
//   classic:   public-domain / historical artists
export type ArtistKind = 'studio' | 'community' | 'classic';

export type User = {
  id: string;
  email: string;
  name: string | null;
  image: string | null;
  bio: string | null;
  portfolio: string | null;
  role: UserRole;
  // Null for non-artist rows (contributors/admins) and unclassified artists.
  artist_kind: ArtistKind | null;
  // Per-sale royalty % for a community artist. Null = use the finance_settings
  // fallback. Ignored for studio / classic artists.
  royalty_percent: number | null;
  created_at: string;
  updated_at: string;
};

// Topic types
/**
 * Topic lifecycle:
 *   upcoming       — pre-launch, contributions not yet open
 *   active         — collecting contributions (deadline in future)
 *   in_production  — deadline passed, artwork being made
 *   completed      — artwork live and available for purchase
 *
 * Transitions:
 *   active        → in_production    via cron (deadline passed)
 *   in_production → completed        when artwork is marked listed
 */
export type TopicStatus = 'upcoming' | 'active' | 'in_production' | 'completed';

export interface ContributionTypeConfig {
  type: string;
  title: string;
  description: string;
  examples: string[];
}

export interface TopicRow {
  id: string;
  title: string;
  description: string;
  long_description: string | null;
  status: TopicStatus;
  target_contributors: number;
  deadline: string | null;
  estimated_completion: string | null;
  completed_date: string | null;
  artist_id: string | null;
  contribution_types: ContributionTypeConfig[];
  prompts: string[];
  created_at: string;
  updated_at: string;
  users?: {
    id: string;
    name: string | null;
    bio: string | null;
    portfolio: string | null;
  } | null;
}

export interface TopicStats {
  contributors: number;
  contributions: number;
  privateContributions: number;
  pendingContributions: number;
}

// Contribution types
export type ContributionType = 'story' | 'photo' | 'sound' | 'link';
export type ContributionStatus = 'pending' | 'approved' | 'rejected';

export type ContributionSource = 'community' | 'studio_seed';

export interface ContributionVersion {
  at: string;
  content: string;
  caption: string | null;
  refine_task_id: string | null;
  instructions: string | null;
}

export interface Contribution {
  id: string;
  topic_id: string;
  type: ContributionType;
  contributor_name: string;
  contributor_email: string;
  contributor_location: string | null;
  content: string;
  caption: string | null;
  consent_given: boolean;
  status: ContributionStatus;
  admin_notes: string | null;
  show_publicly: boolean;
  source: ContributionSource | null;
  previous_versions: ContributionVersion[];
  created_at: string;
  updated_at: string;
}

// Artwork types
export type ArtworkStatus = 'created' | 'listed' | 'sold';

/**
 * Listing metadata generated by the listing-generator agent and applied
 * to Shopify by the listing-sync library.
 *
 * Empty-by-default (`'{}'::jsonb`). Fields stay nullable so the operator
 * can edit individual fields manually without forcing a regen of the
 * others.
 *
 * This is the *creative* surface — fields with no canonical source in
 * the admin DB. Canonical fields (price, vendor, tags, collections)
 * stay on the artwork row / its joined records and are pushed to
 * Shopify/Gelato directly via the sync.
 */
export interface ListingMeta {
  /** SEO meta title for Shopify global.title_tag (≤60 chars). */
  seoTitle: string | null;
  /** SEO meta description for global.description_tag (≤160 chars). */
  seoDescription: string | null;
  /** Open Graph title for social shares (≤60 chars). */
  ogTitle: string | null;
  /** Open Graph description for social shares (≤200 chars). */
  ogDescription: string | null;
  /** ISO timestamp when the agent last wrote this. */
  generatedAt: string | null;
  /** Who set the current values. */
  generatedBy: 'agent' | 'manual' | null;
}

export const EMPTY_LISTING_META: ListingMeta = {
  seoTitle: null,
  seoDescription: null,
  ogTitle: null,
  ogDescription: null,
  generatedAt: null,
  generatedBy: null,
};

export type Artwork = {
  id: string;
  title: string;
  description: string | null;
  image_url: string | null;
  shopify_product_id: string | null;
  shopify_handle: string | null;
  gelato_product_id: string | null;
  gelato_store_id: string | null;
  artist_id: string | null;
  topic_id: string | null;
  status: ArtworkStatus;
  edition_size: number | null;
  edition_sold: number;
  price: number | null;
  currency: string;
  product_type: string | null;
  creation_date: string | null;
  inspiration_summary: string | null;
  contributor_count: number;
  listing_meta: ListingMeta | null;
  /** How the piece was made — drives which creation-cost breakdown applies. */
  creation_source: ArtworkCreationSource;
  /** One-time cost to bring this artwork into existence, in creation_cost_currency. */
  creation_cost: number | null;
  creation_cost_currency: string;
  /** Itemised creation cost: { ai_generation, upscale, mockups, purchase, manual_adjustment }. */
  creation_cost_breakdown: Record<string, unknown>;
  /** Base Gelato print cost for one unit of the chosen size (pre-sale margin estimate). */
  unit_production_cost: number | null;
  /**
   * Composed product-photo set (migration 031), written by the mockup
   * composer: { original, details: [2], framed, inRoom, composedAt }.
   * Null until mockups have been generated for this artwork.
   */
  mockup_urls: MockupUrls | null;
  created_at: string;
  updated_at: string;
};

export interface MockupUrls {
  original: string;
  details: string[];
  framed: string;
  inRoom: string;
  composedAt?: string;
}

export type ArtworkCreationSource =
  | 'ai'
  | 'community'
  | 'purchased'
  | 'public_domain'
  | 'manual';
